disease_specialization_map = {
    "Fungal infection": ["Dermatologist", "General Practitioner"],
    "Allergy": ["Allergist/Immunologist", "General Practitioner"],
    "GERD": ["Gastroenterologist"],
    "Chronic cholestasis": ["Gastroenterologist"],
    "Drug Reaction": ["Allergist/Immunologist", "Dermatologist"],
    "Peptic ulcer disease": ["Gastroenterologist"],
    "AIDS": ["Infectious Disease Specialist"],
    "Diabetes": ["Endocrinologist", "General Practitioner"],
    "Gastroenteritis": ["Gastroenterologist", "General Practitioner"],
    "Bronchial Asthma": ["Pulmonologist", "Allergist/Immunologist"],
    "Hypertension 1": ["Cardiologist", "General Practitioner"],
    "hemorrhoids(piles)": ["Colorectal Surgeon", "General Surgeon"],
    "Cervical spondylosis": ["Orthopedic Surgeon", "Neurologist", "General Practitioner"],
    "Paralysis (brain hemorrhage)": ["Neurologist", "Neurosurgeon"],
    "jaundice": ["Gastroenterologist"],
    "malaria": ["Infectious Disease Specialist", "General Practitioner"],
    "chicken pox": ["Dermatologist", "General Practitioner"],
    "typhoid": ["Infectious Disease Specialist", "General Practitioner"],
    "hepatitis a": ["Gastroenterologist"],
    "hepatitis b": ["Gastroenterologist"],
    "hepatitis c": ["Gastroenterologist"],
    "hepatitis d": ["Gastroenterologist"],
    "hepatitis e": ["Gastroenterologist"],
    "tuberculosis": ["Pulmonologist", "Infectious Disease Specialist"],
    "common cold": ["General Practitioner"],
    "Alcoholic hepatitis": ["Gastroenterologist"],
    "Pneumonia": ["Pulmonologist", "Infectious Disease Specialist"],
    "Dimorphic hemorrhoids(piles)": ["Colorectal Surgeon", "General Surgeon"],
    "heart attack": ["Cardiologist", "Cardiothoracic Surgeon"],
    "varicose veins": ["Vascular Surgeon", "General Practitioner"],
    "Hyperthyroidism": ["Endocrinologist", "General Practitioner"],
    "Hypoglycemia": ["Endocrinologist", "General Practitioner"],
    "Osteoarthritis": ["Orthopedic Surgeon", "Rheumatologist", "General Practitioner"],
    "Arthritis": ["Rheumatologist", "Orthopedic Surgeon", "General Practitioner"],
    "Paroxysmal Positional Vertigo": ["Otolaryngologist", "Neurologist", "General Practitioner"],
    "Acne": ["Dermatologist", "General Practitioner"],
    "Urinary tract infection": ["Urologist", "General Practitioner"],
    "Psoriasis 2": ["Dermatologist", "General Practitioner"],
    "Impetigo": ["Dermatologist", "General Practitioner"],
    "migraine": ["Neurologist", "General Practitioner"]
}